name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 1933 5.14.89.70 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 1933 alyersin@5.14.89.70 << 'EOF'
          cd /home/alyersin/mini-scoala
          git pull
          docker-compose down
          docker-compose up -d --build
          EOF
